# Generated by Django 3.2.7 on 2021-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='media/images/articles')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=8128)),
                ('type', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
