# Generated by Django 3.2.7 on 2021-12-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0008_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
