# Generated by Django 3.2.7 on 2021-12-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_type'),
        ('Articles', '0010_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.type'),
        ),
    ]
