# Generated by Django 3.2.7 on 2021-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0011_alter_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
    ]
