# Generated by Django 3.2.7 on 2022-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='on_slider',
            field=models.BooleanField(default=False),
        ),
    ]
